apiVersion: v0.1.0
envs:
- name: dev-141c102
  path: .xlr8s/envs/dev-141c102/env.yaml
git:
  repoUrl: git@github.com:XI2999-AChandekar/demo-5.1.git
  revision: main
name: demo-1-1b0cf69
vars:
  apps: null
  policy: null
